-- TRIPLEWARE FULL UI & SCRIPT
-- Generated by AI Studio

local CoreGui = game:GetService("CoreGui")
local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")
local RunService = game:GetService("RunService")
local LocalPlayer = Players.LocalPlayer

-- Cleanup previous UI
if CoreGui:FindFirstChild("TriplewareUI") then
    CoreGui.TriplewareUI:Destroy()
end

local TriplewareUI = Instance.new("ScreenGui")
TriplewareUI.Name = "TriplewareUI"
TriplewareUI.ResetOnSpawn = false
TriplewareUI.Parent = CoreGui

-- Floating Button
local FloatingButton = Instance.new("ImageButton")
FloatingButton.Size = UDim2.new(0, 50, 0, 50)
FloatingButton.Position = UDim2.new(0.5, -25, 0.1, 0)
FloatingButton.BackgroundColor3 = Color3.fromRGB(20, 20, 25)
FloatingButton.Image = "rbxassetid://10618928818" -- a nice icon
FloatingButton.Parent = TriplewareUI
local UICorner = Instance.new("UICorner")
UICorner.CornerRadius = UDim.new(1, 0)
UICorner.Parent = FloatingButton
local UIStroke = Instance.new("UIStroke")
UIStroke.Color = Color3.fromRGB(99, 102, 241)
UIStroke.Thickness = 2
UIStroke.Parent = FloatingButton

-- Main Menu
local MainMenu = Instance.new("Frame")
MainMenu.Size = UDim2.new(0, 550, 0, 350)
MainMenu.Position = UDim2.new(0.5, -275, 0.5, -175)
MainMenu.BackgroundColor3 = Color3.fromRGB(15, 15, 20)
MainMenu.ClipsDescendants = true
MainMenu.Visible = false
MainMenu.Parent = TriplewareUI
local MainCorner = Instance.new("UICorner")
MainCorner.CornerRadius = UDim.new(0, 12)
MainCorner.Parent = MainMenu
local MainStroke = Instance.new("UIStroke")
MainStroke.Color = Color3.fromRGB(255, 255, 255)
MainStroke.Transparency = 0.9
MainStroke.Parent = MainMenu

-- Sidebar
local Sidebar = Instance.new("Frame")
Sidebar.Size = UDim2.new(0, 150, 1, 0)
Sidebar.BackgroundColor3 = Color3.fromRGB(10, 10, 15)
Sidebar.Parent = MainMenu
local SidebarLine = Instance.new("Frame")
SidebarLine.Size = UDim2.new(0, 1, 1, 0)
SidebarLine.Position = UDim2.new(1, -1, 0, 0)
SidebarLine.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
SidebarLine.Transparency = 0.9
SidebarLine.Parent = Sidebar

-- Title
local Title = Instance.new("TextLabel")
Title.Size = UDim2.new(1, 0, 0, 40)
Title.Position = UDim2.new(0, 0, 0, 0)
Title.BackgroundTransparency = 1
Title.Text = "TRIPLEWARE"
Title.TextColor3 = Color3.fromRGB(255, 255, 255)
Title.Font = Enum.Font.GothamBlack
Title.TextSize = 14
Title.Parent = Sidebar

-- Bottom Profile
local ProfileFrame = Instance.new("Frame")
ProfileFrame.Size = UDim2.new(1, -20, 0, 40)
ProfileFrame.Position = UDim2.new(0, 10, 1, -50)
ProfileFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 25)
ProfileFrame.Parent = Sidebar
local ProfCorner = Instance.new("UICorner")
ProfCorner.CornerRadius = UDim.new(0, 8)
ProfCorner.Parent = ProfileFrame
local Avatar = Instance.new("ImageLabel")
Avatar.Size = UDim2.new(0, 26, 0, 26)
Avatar.Position = UDim2.new(0, 7, 0.5, -13)
Avatar.BackgroundColor3 = Color3.fromRGB(30, 30, 35)
Avatar.Image = "rbxthumb://type=AvatarHeadShot&id=" .. LocalPlayer.UserId .. "&w=150&h=150"
Avatar.Parent = ProfileFrame
local AvCorner = Instance.new("UICorner")
AvCorner.CornerRadius = UDim.new(1, 0)
AvCorner.Parent = Avatar
local Username = Instance.new("TextLabel")
Username.Size = UDim2.new(1, -45, 1, 0)
Username.Position = UDim2.new(0, 40, 0, 0)
Username.BackgroundTransparency = 1
Username.Text = LocalPlayer.Name
Username.TextColor3 = Color3.fromRGB(255, 255, 255)
Username.TextSize = 10
Username.Font = Enum.Font.GothamBold
Username.TextXAlignment = Enum.TextXAlignment.Left
Username.Parent = ProfileFrame

-- Draggable Button
local dragging = false
local dragInput, dragStart, startPos

FloatingButton.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
        dragging = true
        dragStart = input.Position
        startPos = FloatingButton.Position
    end
end)

FloatingButton.InputEnded:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
        dragging = false
        local delta = input.Position - dragStart
        if delta.Magnitude < 5 then
            if MainMenu.Visible then
                local tw = TweenService:Create(MainMenu, TweenInfo.new(0.3, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {Size = UDim2.new(0, 0, 0, 0), Position = FloatingButton.Position + UDim2.new(0, 25, 0, 25)})
                tw:Play()
                tw.Completed:Wait()
                MainMenu.Visible = false
                FloatingButton.Visible = true
            else
                MainMenu.Size = UDim2.new(0, 0, 0, 0)
                MainMenu.Position = FloatingButton.Position + UDim2.new(0, 25, 0, 25)
                MainMenu.Visible = true
                FloatingButton.Visible = false
                TweenService:Create(MainMenu, TweenInfo.new(0.4, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {Size = UDim2.new(0, 550, 0, 350), Position = UDim2.new(0.5, -275, 0.5, -175)}):Play()
            end
        end
    end
end)

UserInputService.InputChanged:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
        dragInput = input
    end
end)

RunService.RenderStepped:Connect(function()
    if dragging and dragInput then
        local delta = dragInput.Position - dragStart
        FloatingButton.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
    end
end)

-- Content Area
local Content = Instance.new("Frame")
Content.Size = UDim2.new(1, -150, 1, 0)
Content.Position = UDim2.new(0, 150, 0, 0)
Content.BackgroundTransparency = 1
Content.Parent = MainMenu

-- Tabs
local currentTab = nil
local function CreateTab(name, yOffset)
    local btn = Instance.new("TextButton")
    btn.Size = UDim2.new(1, -20, 0, 30)
    btn.Position = UDim2.new(0, 10, 0, yOffset)
    btn.BackgroundColor3 = Color3.fromRGB(20, 20, 25)
    btn.Text = "  " .. name
    btn.TextColor3 = Color3.fromRGB(200, 200, 200)
    btn.Font = Enum.Font.GothamSemibold
    btn.TextSize = 13
    btn.TextXAlignment = Enum.TextXAlignment.Left
    btn.Parent = Sidebar
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 6)
    corner.Parent = btn
    
    local page = Instance.new("ScrollingFrame")
    page.Size = UDim2.new(1, -20, 1, -20)
    page.Position = UDim2.new(0, 10, 0, 10)
    page.BackgroundTransparency = 1
    page.ScrollBarThickness = 2
    page.Visible = false
    page.Parent = Content
    
    local layout = Instance.new("UIListLayout")
    layout.Padding = UDim.new(0, 10)
    layout.Parent = page
    
    btn.MouseButton1Click:Connect(function()
        if currentTab then
            currentTab.btn.BackgroundColor3 = Color3.fromRGB(20, 20, 25)
            currentTab.btn.TextColor3 = Color3.fromRGB(200, 200, 200)
            currentTab.page.Visible = false
        end
        btn.BackgroundColor3 = Color3.fromRGB(99, 102, 241)
        btn.TextColor3 = Color3.fromRGB(255, 255, 255)
        page.Visible = true
        currentTab = {btn = btn, page = page}
    end)
    
    return page, btn
end

local AimPage, AimBtn = CreateTab("Aim Assist", 40)
local VisPage, VisBtn = CreateTab("Visuals", 80)
local MovPage, MovBtn = CreateTab("Movement", 120)
local SkinPage, SkinBtn = CreateTab("Skin Changer", 160)

AimBtn.BackgroundColor3 = Color3.fromRGB(99, 102, 241)
AimBtn.TextColor3 = Color3.fromRGB(255, 255, 255)
AimPage.Visible = true
currentTab = {btn = AimBtn, page = AimPage}

local function CreateToggle(parent, text, defaultState)
    local frame = Instance.new("Frame")
    frame.Size = UDim2.new(1, 0, 0, 35)
    frame.BackgroundColor3 = Color3.fromRGB(20, 20, 25)
    frame.Parent = parent
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 6)
    corner.Parent = frame
    
    local label = Instance.new("TextLabel")
    label.Size = UDim2.new(1, -50, 1, 0)
    label.Position = UDim2.new(0, 10, 0, 0)
    label.BackgroundTransparency = 1
    label.Text = text
    label.TextColor3 = Color3.fromRGB(220, 220, 220)
    label.Font = Enum.Font.Gotham
    label.TextSize = 13
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.Parent = frame
    
    local btn = Instance.new("TextButton")
    btn.Size = UDim2.new(0, 40, 0, 20)
    btn.Position = UDim2.new(1, -50, 0.5, -10)
    btn.BackgroundColor3 = defaultState and Color3.fromRGB(99, 102, 241) or Color3.fromRGB(40, 40, 45)
    btn.Text = ""
    btn.Parent = frame
    local btnCorner = Instance.new("UICorner")
    btnCorner.CornerRadius = UDim.new(1, 0)
    btnCorner.Parent = btn
    
    local circle = Instance.new("Frame")
    circle.Size = UDim2.new(0, 16, 0, 16)
    circle.Position = defaultState and UDim2.new(1, -18, 0.5, -8) or UDim2.new(0, 2, 0.5, -8)
    circle.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    circle.Parent = btn
    local circleCorner = Instance.new("UICorner")
    circleCorner.CornerRadius = UDim.new(1, 0)
    circleCorner.Parent = circle
    
    local state = defaultState
    btn.MouseButton1Click:Connect(function()
        state = not state
        if state then
            TweenService:Create(btn, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(99, 102, 241)}):Play()
            TweenService:Create(circle, TweenInfo.new(0.2), {Position = UDim2.new(1, -18, 0.5, -8)}):Play()
        else
            TweenService:Create(btn, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(40, 40, 45)}):Play()
            TweenService:Create(circle, TweenInfo.new(0.2), {Position = UDim2.new(0, 2, 0.5, -8)}):Play()
        end
    end)
    return frame
end

CreateToggle(AimPage, "Enable Aim Assist", ${config.silentAimEnabled})
CreateToggle(AimPage, "Draw FOV", ${config.fovVisible})
CreateToggle(AimPage, "Silent Aim", false)
CreateToggle(AimPage, "Triggerbot", ${config.triggerBotEnabled})

CreateToggle(VisPage, "Enable ESP", ${config.espEnabled})
CreateToggle(VisPage, "Box ESP", ${config.boxesEnabled})
CreateToggle(VisPage, "Health Bar", ${config.healthBarEnabled})
CreateToggle(VisPage, "Name ESP", true)

CreateToggle(MovPage, "Auto Bhop", ${config.bhopEnabled})
CreateToggle(MovPage, "Jump Bug", false)
CreateToggle(MovPage, "Edge Bug", false)

CreateToggle(SkinPage, "Enable Skin Changer", true)
CreateToggle(SkinPage, "Knife Changer", true)
CreateToggle(SkinPage, "Glove Changer", true)

-- Logic integration
local FOVring = Drawing.new("Circle")
if type(FOVring) ~= "number" then
    FOVring.Visible = ${config.fovVisible}
    FOVring.Thickness = 1.5
    FOVring.Radius = ${config.fovRadius}
    FOVring.Transparency = 1
    FOVring.Color = Color3.fromRGB(139, 92, 246)
    FOVring.Filled = false
    FOVring.Position = workspace.CurrentCamera.ViewportSize / 2

    RunService.RenderStepped:Connect(function()
        FOVring.Visible = ${config.fovVisible}
        FOVring.Radius = ${config.fovRadius}
        FOVring.Position = workspace.CurrentCamera.ViewportSize / 2
    end)
end

print("[Tripleware] Mobile Animated UI Loaded Successfully!")
